name: release
on: workflow_dispatch

permissions:
  contents: read

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  checks:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: npm install --ignore-scripts

      - run: npm audit signatures

      - run: npm run release -- --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
